import { GetServerSideProps } from 'next'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { ItemsPerPage } from '../constants/pagination'
import {
  buildPaginationRequest,
  PaginationResponse,
} from '../dto/pagination.dto'
import { Product } from '../dto/product.dto'
import { http } from '../services/http'
import { Add24Filled } from '@fluentui/react-icons'
import { CartContext } from 'context/cart.context'

const ProductList: React.FC<any> = (props) => {
  const { t } = useTranslation('common')
  const cartCtx = useContext(CartContext)
  const [products, setProducts] = useState<Product[]>([])
  const [pageIndex, setPageIndex] = useState(0)
  const [total, setTotal] = useState(-1)

  useEffect(() => {
    http
      .get<PaginationResponse<Product>>('/products', {
        params: {
          ...buildPaginationRequest(pageIndex, ItemsPerPage),
        },
      })
      .then(({ data }) => {
        if (total == -1) {
          setTotal(data.total)
        }

        setProducts(data.items)
      })
  }, [pageIndex, total])

  function addProductToCart(p: Product) {
    cartCtx.addCartItem({
      productId: p.id,
      quantity: 1,
    })
  }

  return (
    <div className="p-8">
      <Head>
        <title>Order Management System | Product List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-5xl mb-4 text-center">{t('title_product')}</h1>
      <main className="flex flex-col justify-start items-center min-h-screen p-16">
        <div className="flex justify-start min-w-full max-w-full">
          {products.length === 0 && 'No products'}
          {products.length > 0 &&
            products.map((product) => {
              return (
                <div
                  key={product.id}
                  className="flex flex-col border border-solid border-gray-300 hover:shadow-md hover:shadow-slate-300 transition"
                >
                  <div className="p-4">
                    <div>
                      <Image
                        src="/images/default-product-image.png"
                        width={200}
                        height={200}
                        alt={product.name}
                      />
                    </div>
                    <div>{product.name}</div>
                    <div>{product.productPrice}</div>
                  </div>
                  <a
                    className="flex justify-center items-center py-2 px-4 bg-blue-500 hover:bg-blue-600 text-white transition"
                    onClick={() => addProductToCart(product)}
                  >
                    <span className="mr-2">
                      <Add24Filled />
                    </span>
                    <span>{t('add_to_cart')}</span>
                  </a>
                </div>
              )
            })}
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<any> = async ({
  locale,
}) => {
  return {
    props: {
      ...(await serverSideTranslations(locale || 'en', ['common'])),
    },
  }
}

export default ProductList
