basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  dto.UserLogInResponse:
    properties:
      accessToken:
        type: string
    type: object
  dto.UserRegisterDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: integer
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Order System
paths:
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: user information
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserLogInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Register new user
      tags:
      - auth
swagger: "2.0"
