package main

import (
	"flag"
	"fmt"
	"net/http"
	"order-system/config"
	"order-system/database"
	"order-system/handlers"
	"order-system/handlers/dto"
	"order-system/handlers/websocket"
	"os"

	"github.com/asaskevich/govalidator"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/shopspring/decimal"

	echoSwagger "github.com/swaggo/echo-swagger"

	_ "order-system/docs" // docs is generated by Swag CLI, you have to import it.
)

var dbSeed = flag.Bool("seed", false, "whether to perform db seeding")
var dbSeedSample = flag.Bool("seedsample", false, "whether to perform db seeding for sample data")
var dbMigrate = flag.Bool("migrate", false, "whether to perform db migration")

type GoValidatorAdapter struct {
}

func (v *GoValidatorAdapter) Validate(i interface{}) error {
	if _, err := govalidator.ValidateStruct(i); err != nil {
		return err
	}
	return nil
}

func bootstrap() *echo.Echo {
	// chores
	config.LoadConfig()

	database.InitDB()
	db := database.GetDBInstance()

	if *dbMigrate {
		database.AutoMigrate(db)
	}

	if *dbSeed {
		database.SeedDB(db)
	}

	if *dbSeedSample {
		database.SeedSampleData(db)
	}

	// if run migrate or seeding,
	// just run as a cli tool
	if *dbMigrate || *dbSeed || *dbSeedSample {
		os.Exit(0)
	}

	// allow decimal.Decimal value to be a number in the marshalled JSON
	// because these values only use for displaying, so no need to worry about the precison
	decimal.MarshalJSONWithoutQuotes = true

	e := echo.New()

	e.Validator = &GoValidatorAdapter{}

	e.Use(middleware.Logger())

	protectedApiGroup := e.Group("/api")

	jwtConfig := middleware.JWTConfig{
		Claims:     &dto.JwtCustomClaims{},
		SigningKey: []byte(config.GetConfig().JwtSecretKey),
	}

	protectedApiGroup.Use(middleware.JWTWithConfig(jwtConfig))
	handlers.PrivateEndpoints(protectedApiGroup)

	e.GET("/", func(c echo.Context) error {
		return c.JSON(http.StatusOK, "OK")
	})
	handlers.PublicEndpoints(e.Group("/api"))

	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"*"},
		AllowCredentials: true,
	}))

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	go websocket.GetHub().Run()

	return e
}

// @title Order System

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @BasePath /
func main() {
	flag.Parse()
	app := bootstrap()
	config := config.GetConfig()
	app.Logger.Fatal(app.Start(fmt.Sprintf(":%s", config.AppPort)))
}
