import { Button } from 'antd'
import { useTranslation } from 'next-i18next'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import React, { useContext } from 'react'
import { AuthContext } from '../../context/auth.context'
import { CartContext } from '../../context/cart.context'

type Props = {
  children?: React.ReactNode
}

export const LayoutDashboard: React.FC<Props> = (props) => {
  const { t } = useTranslation('common')
  const router = useRouter()
  const authCtx = useContext(AuthContext)
  const cartCtx = useContext(CartContext)
  return (
    <div className="min-w-full">
      <Head>
        <title>Order Management System | Vendor Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl mb-5 text-center">{t('dashboard_title')}</h1>
      <nav className="flex justify-center items-center space-x-4">
        <Link href="/vendors/orders">
          <Button
            type="primary"
            disabled={router.pathname.indexOf('/vendors/orders') >= 0}
          >
            Manage Orders
          </Button>
        </Link>
        <Link href="/vendors/products">
          <Button
            type="primary"
            disabled={router.pathname.indexOf('/vendors/products') >= 0}
          >
            Manage Products
          </Button>
        </Link>
      </nav>
      {props.children}
    </div>
  )
}
